[package]
name = "wow-utils"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
custom_debug = { workspace = true }

[features]
debug-print-all = []
